var faker     = require('faker');
var puppeteer = require('puppeteer');


const AppURI = "http://arjaycodes.com/Indecision";


// Random input from Faker to generate options with.
let i = 0;
let optionsCount = 10;
let options = [];
while (i < optionsCount) {

    options.push(faker.random.words());
    i++;
}

// Puppeteer --
    // Browser-related Variables
    let page;
    let browser;
    let viewportWidth   = 1024;
    let viewportHeight  = 768;
    let timeoutInterval = 16000;

    // Pretest Setup  - Jest
    beforeAll (async () => {

        browser = await puppeteer.launch({
            headless: false,
            slowMo:   80,
            args:     [`--window-size=${viewportWidth},${viewportHeight}`]
        });
        page = await browser.newPage();
        await page.setViewport({width: viewportWidth, height: viewportHeight});
    });

    // Posttest Setup - Jest
    afterAll (async () => {

        //await browser.close();
    });

    // Test #1 - User should be able to input any data they choose into the input field (It is their own decisions after all).
    describe ("Choices Input Form", () => {
        test("User should be able to input any for of data they like, as it is up to them what choices they are trying to make.", async () => {

            await page.goto(AppURI);
            // Test Steps
                // 1: Wait for input field to load on page.
                    await page.waitForSelector('input[name="option"]').then(() => {
                        console.log(`input[name="option"] loaded.`);
                    });
                    // await page.click('input[name="option"]');
                    // await page.type('input[name="option"]', "Test");


                // 2: Enter each choice generated by Faker into the field.
                    console.log(`Entering "${options[0]}"...`);
                    await page.type('input[name="option"]', options[0]);
                    await page.press('enter');

            // Output screenshot & PDF
            // page.screenshot({path: 'test1.png'});
            // page.pdf({path: 'test1.pdf', format: 'A4'});
        }, timeoutInterval);
    });
