console.log('app.js is running.')

// JSX

let app = {
    title: "Indecision",
    subtitle: "Make tricky decisions with the help of ReactJS!"
};
let user = {
    name:     "Joe Schmoe",
    age:      31,
    location: 'Yew Nork City'
};

const getUserLocation = (location) => {
    return (location != null && location != '') ? <p>Location: {location}</p> : null;
}

const template = (
    <div>
        <h1 className="head" id="jsx-h1">{app.title}</h1>
        <br />
        <span>{app.subtitle}</span>
        <ol>
            <li> One Thing </li>
            <li> Two Thing </li>
            <li> Red Thing </li>
            <li> Blu Thing </li>
        </ol>
    </div>
);

const userInfo = (
    <div>
        <h1>{user.name}</h1>
        <p>Age:      {user.age}</p>
        {getUserLocation(user.location)}
    </div>
);

// let template = React.createElement(
//     "h1",
//     {
//         id:        "jsx-h1",
//         className: "head"
//     },
//     "This is an element generated by React."
// );
// same as template = <h1 class="head" id="jsx-h1"> This is an element generated by React.</h1>
let appRoot   = document.getElementById('react-template-target');
let userRoot  = document.getElementById('user');
ReactDOM.render(template, appRoot);
ReactDOM.render(userInfo, userRoot);